generatorName: go
templateDir: ./.generator/templates
outputDir: ./sdk
additionalProperties:
  enumClassPrefix: true
  generateInterfaces: true
  packageName: sdk
  useOneOfDiscriminatorLookup: true
  disallowAdditionalPropertiesIfNotPresent: false
files:
  api_application_test.go: {}
  api_group_test.go: {}
  api_idp_test.go: {}
  api_policy_test.go: {}
  api_user_schema_test.go: {}
  api_user_test.go: {}
  cache.go: {}
  configuration_test.go: {}
  gocache.go: {}
  main_test.go: {}
  noopcache.go: {}
  test_helpers.go: {}
  user_agent.go: {}
