version: 2.1

commands:
  install_go_tools:
    description: "Install required Go development tools"
    steps:
      - run:
          name: Install Go Tools
          command: make tools

jobs:
  setup:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - install_go_tools
      - run:
          name: Download Dependencies
          command: make dep
      # Cache dependencies between jobs
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  generate:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Generate Command Files
          command: make generate-cmd
      # Store generated files for later jobs
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - attach_workspace:
          at: .
      - run:
          name: Format Check
          command: make fmt
      - run:
          name: Build
          command: make build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: make test
          environment:
            TEST: ./...

workflows:
  version: 2
  build-test:
    jobs:
      - setup
      - generate:
          requires:
            - setup
      - build:
          requires:
            - generate
      - test:
          requires:
            - build
